version: "3"
services:
  pg:
    image: "postgres:latest"
    container_name: pg
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data/
volumes:
  pg-data:
