const receipts = [
	{
		timeOfPurchase: "2021-07-11T11:20:57.733Z",
		products: [
			{
				product: "wild rice",
				price: 6.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 3.55,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 2.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 3.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 7.33,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 7.46,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 31.15,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-08-04T17:23:10.861Z",
		products: [
			{
				product: "coca cola zero",
				price: 7.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 2.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 7.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 1.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 2.27,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 3.26,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 7.38,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 6.96,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 39.19,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-15T15:20:50.429Z",
		products: [
			{
				product: "heineken",
				price: 7.98,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 7.98,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-08T02:53:09.804Z",
		products: [
			{
				product: "oreos",
				price: 4.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 8.27,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 8.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 2.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 5.15,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 3.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 5.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 1.75,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 5.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 5.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 6.35,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 56.06,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-30T02:10:12.097Z",
		products: [
			{
				product: "milk",
				price: 3.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 3.55,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 8.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 8.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 2.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 1.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 4.35,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 7.85,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 1.83,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 1.58,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 4.76,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 48.89,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-24T14:48:21.614Z",
		products: [
			{
				product: "brie",
				price: 7.85,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 5.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 4.14,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 17.61,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-15T08:00:12.080Z",
		products: [
			{
				product: "fanta",
				price: 5.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 4.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 2.35,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 3.98,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 7.37,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 23.04,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-28T22:44:31.771Z",
		products: [
			{
				product: "bread",
				price: 6.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 1.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 8.84,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 2.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 1.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 8.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 1.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 2.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 1.86,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 35.68,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-03T03:22:22.798Z",
		products: [
			{
				product: "crips",
				price: 3.98,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 5.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 7.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 2.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 3.02,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 5.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 8.83,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 1.77,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 39.07,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-29T05:19:49.093Z",
		products: [
			{
				product: "sausages",
				price: 6.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 2.97,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 9.46,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-15T23:39:10.659Z",
		products: [
			{
				product: "sprite",
				price: 4.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 6.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 7.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 6.05,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 25.33,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-24T00:08:13.930Z",
		products: [
			{
				product: "amaranth",
				price: 1.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 6.1,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 7.99,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-09T22:51:23.409Z",
		products: [
			{
				product: "tapioca",
				price: 6.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 4.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 3.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 2.87,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 5.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 3.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 5.44,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 7.16,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 7.14,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 7.33,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 54.37,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-30T02:03:11.702Z",
		products: [
			{
				product: "salami",
				price: 4.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 2.84,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 4.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 3.98,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 6.74,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 1.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 1.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 8.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 7.57,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 6.99,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 48.42,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-03T11:44:04.884Z",
		products: [
			{
				product: "milk",
				price: 3.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 7.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 6.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 2.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 7.77,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 7.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 4.89,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 39.14,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-05-29T21:45:55.362Z",
		products: [
			{
				product: "red wine",
				price: 7.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 7.44,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 1.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 3.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 3.58,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 5.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 8.42,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 37,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-28T23:42:32.544Z",
		products: [
			{
				product: "arrowroot",
				price: 4.39,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 4.39,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-08-08T09:46:30.124Z",
		products: [
			{
				product: "rocket salad",
				price: 1.53,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 1.53,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-24T17:35:42.454Z",
		products: [
			{
				product: "Oatmeal Raisin Cookies",
				price: 7.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 1.53,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 6.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 2.99,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 4.15,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 5.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 1.98,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 2.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 5.98,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 6.8,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 45.93,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-30T02:18:29.563Z",
		products: [
			{
				product: "sweet chili sauce",
				price: 2.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 6.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 1.52,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 10.57,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-05-27T21:58:17.685Z",
		products: [
			{
				product: "Sugar Cookies",
				price: 7.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 4.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 5.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 6.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 6.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 3.1,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 42.52,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-05T09:41:58.498Z",
		products: [
			{
				product: "wild rice",
				price: 7.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 2.65,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 4.61,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 3.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 8.47,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 27.27,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-31T03:47:03.441Z",
		products: [
			{
				product: "buckwheat",
				price: 3.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 8.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 2.57,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 14.47,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-22T22:13:07.689Z",
		products: [
			{
				product: "Oatmeal Raisin Cookies",
				price: 3.54,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 3.54,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-08T07:24:52.294Z",
		products: [
			{
				product: "sausages",
				price: 8.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 8.28,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 7.92,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 2.77,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 3.87,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 31.06,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-21T03:16:56.020Z",
		products: [
			{
				product: "Biscotti Cookies",
				price: 7.55,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 6.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 5.65,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 1.96,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 5.46,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 27.05,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-13T07:32:21.339Z",
		products: [
			{
				product: "sweet chili sauce",
				price: 7.79,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 8.94,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 3.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 7.53,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 2.07,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 4.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 4.92,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 5.17,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 4.81,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 53.78,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-19T06:13:59.608Z",
		products: [
			{
				product: "chips",
				price: 4.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 2.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 8.07,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 6.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 5.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 8.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 8.02,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 43.61,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-17T04:27:40.356Z",
		products: [
			{
				product: "cheese",
				price: 1.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 1.79,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 7.73,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 10.6,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-21T15:45:21.508Z",
		products: [
			{
				product: "Macaron Cookies",
				price: 1.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 8.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 5.98,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 16.05,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-10T07:14:40.279Z",
		products: [
			{
				product: "orange juice",
				price: 2.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 4.2,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 6.44,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-14T13:46:09.905Z",
		products: [
			{
				product: "orange juice",
				price: 5.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 7.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 2.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 1.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 7.83,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 5.94,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 6.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 2.93,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 40.5,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-22T07:02:09.513Z",
		products: [
			{
				product: "wild rice",
				price: 7.7,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 1.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 7.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 5.57,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 4.58,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 7.97,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 34.64,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-01T09:44:09.670Z",
		products: [
			{
				product: "sorghum",
				price: 3.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 1.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 3.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 6.71,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 2.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 3.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 3.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 6.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 7.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 6.15,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 44.73,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-08T00:12:24.856Z",
		products: [
			{
				product: "fanta",
				price: 5.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 6.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 4.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 5.17,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 2.84,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 24.38,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-11T05:17:12.846Z",
		products: [
			{
				product: "stella",
				price: 6.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 8.71,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 6.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 7.06,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 8.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 1.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 7.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 4.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 8.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 4.99,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 3.45,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 67.35,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-18T00:24:36.125Z",
		products: [
			{
				product: "tomatoes",
				price: 5.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 3.37,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 7.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 6.46,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 6.8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 5.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 6.66,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 41.49,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-24T19:10:47.462Z",
		products: [
			{
				product: "Biscotti Cookies",
				price: 3.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 3.32,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 5.58,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 8.11,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 20.5,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-27T07:05:12.042Z",
		products: [
			{
				product: "Sugar Cookies",
				price: 4.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 4.95,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 7.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 7.37,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 2.57,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 4.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 6.23,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 36.92,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-18T22:44:35.547Z",
		products: [
			{
				product: "frozen peas",
				price: 5.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 1.65,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 1.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 5.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 2.7,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 8.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 5.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 7.28,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 6.61,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 7.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 5.39,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 57.41,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-14T00:46:40.928Z",
		products: [
			{
				product: "stella",
				price: 6.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 3.94,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 1.94,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 3.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 5.99,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 1.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 6.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 2.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 3.58,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 4.13,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 40.38,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-12T04:50:55.436Z",
		products: [
			{
				product: "ketchup",
				price: 1.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 3.47,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 2.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 6.2,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 12.89,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 4443,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-06T21:52:44.713Z",
		products: [
			{
				product: "lettuce",
				price: 4.06,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 5.57,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 5.96,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 6.55,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 3.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 6.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 1.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 3.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 8.02,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 2.69,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 47.55,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-25T11:55:34.202Z",
		products: [
			{
				product: "coca cola",
				price: 8.29,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 3.8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 6.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 8.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 3.99,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 8.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 8.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 4.78,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 54.33,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 4443,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-20T11:32:31.801Z",
		products: [
			{
				product: "Chocolate Chip Cookies",
				price: 3.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 7.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 5.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 7.79,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 5.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 4.91,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 33.96,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-28T21:39:47.871Z",
		products: [
			{
				product: "tapioca",
				price: 1.07,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 8.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 2.96,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 12.34,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-12T13:33:25.763Z",
		products: [
			{
				product: "tapioca",
				price: 6.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 6.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 3.99,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 1.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 8.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 2.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 8.96,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 2.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 4.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 6.46,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 2.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 6.26,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 60.34,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-08-02T07:04:06.983Z",
		products: [
			{
				product: "Macaroon Cookies",
				price: 7.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 1.61,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 2.43,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 11.54,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-08-01T20:57:50.028Z",
		products: [
			{
				product: "pork chops",
				price: 4.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 4.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 6.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 8.64,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 23.94,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-11T20:57:33.977Z",
		products: [
			{
				product: "rocket salad",
				price: 8.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 7.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 5.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 4.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 1.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 3.28,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 2.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 7.44,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 40.92,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-20T19:04:16.032Z",
		products: [
			{
				product: "Shortbread Cookies",
				price: 7.33,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 5.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 8.74,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 2.22,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 23.7,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-22T23:19:37.118Z",
		products: [
			{
				product: "ketchup",
				price: 5.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 7.4,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 12.49,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-04T00:58:39.561Z",
		products: [
			{
				product: "stella",
				price: 8.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 6.47,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 6.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 2.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 5.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 2.16,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 5.25,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 7.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 5.27,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 4.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 3.61,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 4.38,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 62.72,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-05-31T19:44:24.739Z",
		products: [
			{
				product: "sweetcorn",
				price: 3.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 5.77,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 3.63,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 12.6,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-05T00:51:54.425Z",
		products: [
			{
				product: "teff",
				price: 6.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 7.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 4.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 7.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 5.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 8.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 8.79,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 4.98,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 6.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 5.83,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 65.09,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-08-08T07:50:26.483Z",
		products: [
			{
				product: "mustard",
				price: 3.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 1.06,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 8.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 8.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 3.77,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 5.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 2.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 8.17,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 4.77,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 3.7,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 4.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 5.82,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 59.02,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-18T09:02:14.357Z",
		products: [
			{
				product: "Chocolate Chip Cookies",
				price: 4.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 2.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 8.29,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 2.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 3.35,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 6.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 1.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 4.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 4.02,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 4.37,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 41.36,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-20T04:58:45.631Z",
		products: [
			{
				product: "rump steak",
				price: 2.7,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 2.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 4.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 1.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 4.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 3.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 3.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 2.78,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 6.62,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 31.46,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-05-31T19:21:33.696Z",
		products: [
			{
				product: "rump steak",
				price: 3.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 2.58,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 3.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 4.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 7.18,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 4.78,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 7.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 6.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 5.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 8.33,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 54.56,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-30T06:52:09.023Z",
		products: [
			{
				product: "red wine",
				price: 8.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 2.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 7.14,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 3.75,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 4.03,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 6.8,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 32.49,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-11T09:07:46.618Z",
		products: [
			{
				product: "amaranth",
				price: 2.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 7.92,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 1.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 4.05,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 8.05,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 6.52,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 5.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 2.15,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 5.83,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 2.45,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 46.35,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 4443,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-06T06:28:17.227Z",
		products: [
			{
				product: "stella",
				price: 7.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 8.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 1.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 5.98,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 23.72,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-29T21:02:52.852Z",
		products: [
			{
				product: "stella",
				price: 1.37,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 7.03,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 6.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 8.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 6.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 6.83,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 2.37,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 3.41,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 42.74,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-10T00:32:21.705Z",
		products: [
			{
				product: "mustard",
				price: 3,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 5.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 6.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 2.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 1.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 4.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 2.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 6.95,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 1.73,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 34.91,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-05T04:19:55.975Z",
		products: [
			{
				product: "bread",
				price: 5.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 5.47,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 11.23,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-15T08:57:57.504Z",
		products: [
			{
				product: "salami",
				price: 3.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 8.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 4.53,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 2.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 7.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 8.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 3.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 6.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 2.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 4.9,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 53.14,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-02T22:28:35.032Z",
		products: [
			{
				product: "wild rice",
				price: 3.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 3.57,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 2.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 5.14,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 13.82,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-11T16:10:16.841Z",
		products: [
			{
				product: "sorghum",
				price: 1.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 2.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 8.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 6.39,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 19.35,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 4443,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-08T07:53:24.533Z",
		products: [
			{
				product: "sausages",
				price: 5.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 3.29,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 1.79,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 8.17,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 1.07,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 8.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 5.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 7.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 5.75,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 4.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 6.5,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 58.36,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-18T16:53:47.689Z",
		products: [
			{
				product: "cookies",
				price: 7.86,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 7.86,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 4443,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-28T12:19:44.543Z",
		products: [
			{
				product: "wild rice",
				price: 3.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 8.47,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 2.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 7.47,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 22.13,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-09T12:36:30.898Z",
		products: [
			{
				product: "Sugar Cookies",
				price: 3.84,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 2.27,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 8.92,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 2.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 4.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 1.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 7.38,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 2.5,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 37.56,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-15T16:49:14.790Z",
		products: [
			{
				product: "Shortbread Cookies",
				price: 5.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 6.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 6.35,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 4.14,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 7.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 2.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 3.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 1.84,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 7.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 2.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 7.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 8.3,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 64.95,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-29T18:04:10.190Z",
		products: [
			{
				product: "chorizo",
				price: 4.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 1.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 7.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 2.26,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 6.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 4.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 2.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 4.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 7.6,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 40.69,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-15T03:44:20.493Z",
		products: [
			{
				product: "lettuce",
				price: 3.77,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 5.14,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 5.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 1.02,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 7.29,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 8.14,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 1.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 7.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 1.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 7.87,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 5.14,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 53.12,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-09T08:36:04.829Z",
		products: [
			{
				product: "chips",
				price: 7.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 2.06,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 5.84,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 15.13,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-05-28T17:58:56.540Z",
		products: [
			{
				product: "frozen peas",
				price: 2.87,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 5.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 7.46,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 4.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 7.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 1.38,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 28.54,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-05T18:19:34.731Z",
		products: [
			{
				product: "tapioca",
				price: 8.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 3.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 4.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 8.61,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 1.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 4.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 3,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 34.62,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-15T17:54:28.905Z",
		products: [
			{
				product: "frozen peas",
				price: 2.78,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 3.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 2.28,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 6.18,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 14.28,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-24T12:37:08.061Z",
		products: [
			{
				product: "white wine",
				price: 1.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 6.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 6.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 3.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 8.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 3.85,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 6.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 6.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 5.65,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 7.51,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 56.52,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-05-29T13:38:54.450Z",
		products: [
			{
				product: "amaranth",
				price: 8.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 7.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 8.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 5.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 6.78,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 1.15,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 4.29,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 47.74,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-14T18:02:57.250Z",
		products: [
			{
				product: "oreos",
				price: 7.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 1.16,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 8.58,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 2.99,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 5.87,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 6.44,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 8.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 5.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 8.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 8.53,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 3.82,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 67.37,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-05-30T23:46:10.154Z",
		products: [
			{
				product: "orange juice",
				price: 6.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 8.61,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 5.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 2.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 6.8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 1.3,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 8.24,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 39.24,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-26T20:03:39.201Z",
		products: [
			{
				product: "oreos",
				price: 2.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 2.46,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 4.71,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 9.57,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-08-02T06:24:43.789Z",
		products: [
			{
				product: "red wine",
				price: 6.14,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 6.14,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-08-04T01:04:39.577Z",
		products: [
			{
				product: "fanta",
				price: 5.85,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 4.15,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 4.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 6.05,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 20.27,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-09T11:17:34.683Z",
		products: [
			{
				product: "amaranth",
				price: 3.16,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 7.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 5.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 1.65,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 1.27,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 8.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 2.94,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 3.18,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 7.44,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 3.4,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 44.42,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-06T18:46:21.439Z",
		products: [
			{
				product: "tomatoes",
				price: 6.07,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 8.37,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 1.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 1.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 7.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 1.03,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 8.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 3.18,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 8.93,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 46.62,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-18T15:38:24.187Z",
		products: [
			{
				product: "sausages",
				price: 2.26,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 6.8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 3.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 3.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 8.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 4.77,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 29.35,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-14T02:06:31.549Z",
		products: [
			{
				product: "ketchup",
				price: 4.96,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 4.96,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-07T06:54:45.543Z",
		products: [
			{
				product: "millet",
				price: 8.78,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 7.35,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 8.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 5.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 2.45,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 32.39,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-05-29T15:44:03.357Z",
		products: [
			{
				product: "rump steak",
				price: 3.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 4.17,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 5.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 8.1,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 21.42,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-15T04:47:31.044Z",
		products: [
			{
				product: "crips",
				price: 2.47,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 5.19,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 7.66,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 4443,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-05-31T15:09:57.648Z",
		products: [
			{
				product: "rocket salad",
				price: 1.43,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 1.43,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-14T22:23:23.902Z",
		products: [
			{
				product: "Macaroon Cookies",
				price: 8.87,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 4.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 1.06,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 7.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 4.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 5.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 5.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 7.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 4.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 8.25,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 57.15,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-25T16:15:27.715Z",
		products: [
			{
				product: "sweet chili sauce",
				price: 3.98,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 4.7,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 8.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 3.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 7.25,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 4.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 7.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 6.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 3.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 1.47,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 50.39,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-07-06T07:05:40.303Z",
		products: [
			{
				product: "mustard",
				price: 4.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 8.27,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 7.17,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 1.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 6.33,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 4.47,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 3.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 6.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 8.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 4.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 6.03,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 61.38,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-06-01T15:56:48.544Z",
		products: [
			{
				product: "salad",
				price: 5.96,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 7.61,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 3.32,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 1.32,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 18.21,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-08-05T12:11:42.201Z",
		products: [
			{
				product: "tomatoes",
				price: 1.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 5.95,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 7.14,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		store: 1,
	},
	{
		timeOfPurchase: "2021-05-31T12:28:25.619Z",
		products: [
			{
				product: "sweetcorn",
				price: 5.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 2.52,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 8.14,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		store: 1,
	},
];
let i = 0;
async function sendReceipt() {
	console.log(receipts[i]);
	const url = "http://localhost:3005/receipts";
	const response = await fetch(url, {
		method: "POST",
		mode: "cors",
		body: JSON.stringify(receipts[i]),
		headers: {
			"Content-Type": "application/json",
			// 'Content-Type': 'application/x-www-form-urlencoded',
		},
	});
	const body = await response.json();
	const div = document.getElementById("div");
	div.innerHTML = body.qrcode;
	i += 1;
}

const button = document.getElementById("button");
button.onclick = sendReceipt;
