const receipts = [
	{
		id: "0",
		timeOfPurchase: "2021-07-10T14:46:41.588Z",
		products: [
			{
				product: "oreos",
				price: 3.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 6.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 1.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 5.74,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 7.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 5.44,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 30.79,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		id: "1",
		timeOfPurchase: "2021-07-19T16:05:04.768Z",
		products: [
			{
				product: "rocket salad",
				price: 2.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 4.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 6.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 3.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 1.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 7.8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 3.15,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 2.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 5.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 1.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 4.78,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 44.12,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		store: 1,
	},
	{
		id: "2",
		timeOfPurchase: "2021-07-25T19:47:25.550Z",
		products: [
			{
				product: "sweet chili sauce",
				price: 3.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 1.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 1.53,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 3.14,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 10.12,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		store: 1,
	},
	{
		id: "3",
		timeOfPurchase: "2021-06-17T01:43:31.888Z",
		products: [
			{
				product: "Sugar Cookies",
				price: 4.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 3.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 5.37,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 7.92,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 4.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 2.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 5.98,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 8.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 5.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 4.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 3.12,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 54.55,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		store: 1,
	},
	{
		id: "4",
		timeOfPurchase: "2021-07-04T05:27:53.071Z",
		products: [
			{
				product: "tomatoes",
				price: 4.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 5.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 4.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 3.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 7.3,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 4.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 8.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 1.46,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 8.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 4.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 2.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 7.9,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 61.22,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		store: 1,
	},
	{
		id: "5",
		timeOfPurchase: "2021-07-29T06:06:42.135Z",
		products: [
			{
				product: "orange juice",
				price: 3.71,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 7.95,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 1.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 7.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 8.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 3.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 4.78,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 8.99,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 46.91,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		store: 1,
	},
	{
		id: "6",
		timeOfPurchase: "2021-05-31T01:26:53.032Z",
		products: [
			{
				product: "arrowroot",
				price: 8.98,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 1.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 8.27,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 7.02,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 3.72,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 29.08,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		store: 1,
	},
	{
		id: "7",
		timeOfPurchase: "2021-06-08T15:08:43.205Z",
		products: [
			{
				product: "Macaroon Cookies",
				price: 5.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 4.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 6.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 5.05,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 7.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 8.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 7.47,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 45.55,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		store: 1,
	},
	{
		id: "8",
		timeOfPurchase: "2021-07-10T20:19:15.600Z",
		products: [
			{
				product: "pepsi",
				price: 8.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 2.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 5.28,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 8.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 8.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 3.25,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 4.88,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 42.09,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		id: "9",
		timeOfPurchase: "2021-07-09T08:24:39.996Z",
		products: [
			{
				product: "Shortbread Cookies",
				price: 5.33,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 4.95,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 3.27,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 13.55,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		id: "10",
		timeOfPurchase: "2021-06-29T12:23:08.324Z",
		products: [
			{
				product: "salami",
				price: 4.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 4.65,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 4.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 1.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 8.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 2.37,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 3.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 7.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 8.74,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 7.33,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 52.91,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		store: 1,
	},
	{
		id: "11",
		timeOfPurchase: "2021-08-03T01:26:48.271Z",
		products: [
			{
				product: "orange juice",
				price: 2.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 3.18,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 5.68,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		id: "12",
		timeOfPurchase: "2021-06-23T08:30:50.951Z",
		products: [
			{
				product: "cucumber",
				price: 2.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 8.58,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 7.79,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 2.74,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 3.29,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 3.96,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 28.92,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		store: 1,
	},
	{
		id: "13",
		timeOfPurchase: "2021-06-01T18:56:37.992Z",
		products: [
			{
				product: "chips",
				price: 3.74,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 4.79,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 8.53,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		id: "14",
		timeOfPurchase: "2021-06-09T13:48:33.712Z",
		products: [
			{
				product: "lettuce",
				price: 4.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 2.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 3.75,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 3.27,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 13.72,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		id: "15",
		timeOfPurchase: "2021-07-19T13:31:54.576Z",
		products: [
			{
				product: "Oatmeal Raisin Cookies",
				price: 8.87,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 1.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 6.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 6.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 6.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 3.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 3.8,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 38.14,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		id: "16",
		timeOfPurchase: "2021-06-26T11:07:04.073Z",
		products: [
			{
				product: "buckwheat",
				price: 5.95,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 4.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 4.94,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 4.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 3.84,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 8.94,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 3.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 4.09,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 40.85,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		store: 1,
	},
	{
		id: "17",
		timeOfPurchase: "2021-07-18T09:01:47.940Z",
		products: [
			{
				product: "stella",
				price: 4.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 1.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 3.33,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 7.29,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 1.32,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 18.19,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		store: 1,
	},
	{
		id: "18",
		timeOfPurchase: "2021-08-03T15:00:12.048Z",
		products: [
			{
				product: "stella",
				price: 8.06,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 6.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 6.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 8.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 2.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 1.56,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 33.3,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		id: "19",
		timeOfPurchase: "2021-06-29T08:04:12.262Z",
		products: [
			{
				product: "arrowroot",
				price: 6.15,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 2.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 5.8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 5.04,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 19.92,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		store: 1,
	},
	{
		id: "20",
		timeOfPurchase: "2021-06-18T13:28:46.190Z",
		products: [
			{
				product: "fanta",
				price: 6.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 1.48,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 7.72,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		store: 1,
	},
	{
		id: "21",
		timeOfPurchase: "2021-06-21T12:51:45.431Z",
		products: [
			{
				product: "crips",
				price: 6.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 4.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 6.57,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 7.61,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 25.36,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		store: 1,
	},
	{
		id: "22",
		timeOfPurchase: "2021-06-12T05:33:24.341Z",
		products: [
			{
				product: "rump steak",
				price: 1.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 8.79,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 7.12,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 17.77,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		id: "23",
		timeOfPurchase: "2021-06-25T12:23:57.183Z",
		products: [
			{
				product: "buckwheat",
				price: 3.1,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 3.1,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		store: 1,
	},
	{
		id: "24",
		timeOfPurchase: "2021-05-28T05:23:30.738Z",
		products: [
			{
				product: "cookies",
				price: 1.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 4.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 4.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 3.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 6.53,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 20.97,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 4443,
		misc: "",
		store: 1,
	},
	{
		id: "25",
		timeOfPurchase: "2021-06-30T01:06:08.570Z",
		products: [
			{
				product: "Oatmeal Raisin Cookies",
				price: 7.57,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 8.03,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 15.6,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		store: 1,
	},
	{
		id: "26",
		timeOfPurchase: "2021-07-14T16:53:07.062Z",
		products: [
			{
				product: "orange juice",
				price: 7.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 7.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 1.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 4.02,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 1.95,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 8.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 3.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 7.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 5.29,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 7.2,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 53.47,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		store: 1,
	},
	{
		id: "27",
		timeOfPurchase: "2021-08-04T05:07:08.913Z",
		products: [
			{
				product: "stella",
				price: 5.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 2.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 2.05,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 1.47,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 7.69,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 19.49,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		store: 1,
	},
	{
		id: "28",
		timeOfPurchase: "2021-07-10T18:19:43.875Z",
		products: [
			{
				product: "brie",
				price: 1.32,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 8.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 3.29,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 8.96,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 5.99,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 8.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 4.17,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 8.71,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 8.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 3.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 6.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 2.71,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 70.14,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		store: 1,
	},
	{
		id: "29",
		timeOfPurchase: "2021-07-09T14:01:48.610Z",
		products: [
			{
				product: "chicken breast 450g",
				price: 3.71,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 8.47,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 7.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 4.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 4.85,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 7.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 6.3,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 6.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 2.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 6.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 6.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 6.41,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 71.58,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		id: "30",
		timeOfPurchase: "2021-06-02T09:41:51.695Z",
		products: [
			{
				product: "cheese",
				price: 2.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 3.25,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 8.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 7.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 6.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 7.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 7.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 7.44,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 5.53,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 8.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 5.53,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 70.5,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		store: 1,
	},
	{
		id: "31",
		timeOfPurchase: "2021-06-22T23:25:02.907Z",
		products: [
			{
				product: "chicken breast 450g",
				price: 7.87,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 1.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 3.1,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 12.31,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		store: 1,
	},
	{
		id: "32",
		timeOfPurchase: "2021-06-12T00:49:57.463Z",
		products: [
			{
				product: "Shortbread Cookies",
				price: 5.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 8.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 1.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 7.28,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 2.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 7.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 1.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 5.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 2.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 5.25,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 47.69,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		store: 1,
	},
	{
		id: "33",
		timeOfPurchase: "2021-06-30T05:15:17.484Z",
		products: [
			{
				product: "tooth brush",
				price: 2.05,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 3.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 2.05,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 8.07,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		store: 1,
	},
	{
		id: "34",
		timeOfPurchase: "2021-06-16T06:57:23.639Z",
		products: [
			{
				product: "sprite",
				price: 7.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 1.18,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 5.03,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 2.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 8.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 8.75,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 4.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 2.06,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 2.02,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 42.98,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 4443,
		misc: "",
		store: 1,
	},
	{
		id: "35",
		timeOfPurchase: "2021-07-30T13:47:25.020Z",
		products: [
			{
				product: "cookies",
				price: 7.87,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 1.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 3.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 4.38,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 7.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 5.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 8.05,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 3.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 8.54,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 50.3,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		store: 1,
	},
	{
		id: "36",
		timeOfPurchase: "2021-06-03T10:10:28.266Z",
		products: [
			{
				product: "avocados",
				price: 1.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 1.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 1.33,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 4.49,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		store: 1,
	},
	{
		id: "37",
		timeOfPurchase: "2021-06-03T09:10:48.791Z",
		products: [
			{
				product: "chips",
				price: 8.26,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 7.16,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 15.42,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		store: 1,
	},
	{
		id: "38",
		timeOfPurchase: "2021-06-03T20:41:30.083Z",
		products: [
			{
				product: "fanta",
				price: 2.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 4.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 8.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 7.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 4.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 4.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 8.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 1.14,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 7.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 7.85,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 6.87,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 63.19,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		store: 1,
	},
	{
		id: "39",
		timeOfPurchase: "2021-05-29T08:38:05.869Z",
		products: [
			{
				product: "arrowroot",
				price: 1.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 1.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 8.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 2.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 8.17,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 7.26,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 3.53,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 2.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 8.74,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 5.7,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 1.77,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 52.03,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		id: "40",
		timeOfPurchase: "2021-08-03T19:46:48.531Z",
		products: [
			{
				product: "sprite",
				price: 5.17,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 3.44,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 6.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 6.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 4.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 4.13,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 29.52,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		store: 1,
	},
	{
		id: "41",
		timeOfPurchase: "2021-07-28T06:16:38.938Z",
		products: [
			{
				product: "Sugar Cookies",
				price: 6.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 3.47,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 8.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 1.87,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 7.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 1.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 1.78,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 6.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 7.95,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 3.19,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 48.74,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		id: "42",
		timeOfPurchase: "2021-07-21T05:47:12.364Z",
		products: [
			{
				product: "fanta",
				price: 3.25,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 7.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 4.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 7.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 5.28,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 7.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 3.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 7.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 3.19,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 50.06,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		id: "43",
		timeOfPurchase: "2021-07-15T02:00:31.259Z",
		products: [
			{
				product: "chips",
				price: 6.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 8.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 8.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 7.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 5.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 5.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 7.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 2.18,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 5.02,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 3.12,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 59.66,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		store: 1,
	},
	{
		id: "44",
		timeOfPurchase: "2021-06-11T04:56:38.001Z",
		products: [
			{
				product: "sweet chili sauce",
				price: 8.44,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 1.08,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 9.52,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		store: 1,
	},
	{
		id: "45",
		timeOfPurchase: "2021-06-14T22:32:05.774Z",
		products: [
			{
				product: "coca cola",
				price: 5.56,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 5.56,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		id: "46",
		timeOfPurchase: "2021-06-26T20:47:05.591Z",
		products: [
			{
				product: "crips",
				price: 6.57,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 2.46,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 3.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 6.32,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 1.32,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 4.99,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 6.3,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 31.2,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 4443,
		misc: "",
		store: 1,
	},
	{
		id: "47",
		timeOfPurchase: "2021-08-07T08:50:01.214Z",
		products: [
			{
				product: "Macaroon Cookies",
				price: 1.55,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 6.58,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 2.14,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 6.35,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 2.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 5.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 2.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 3.02,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 29.49,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		store: 1,
	},
	{
		id: "48",
		timeOfPurchase: "2021-07-28T20:22:23.154Z",
		products: [
			{
				product: "crips",
				price: 8.84,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 7.48,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 16.32,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		store: 1,
	},
	{
		id: "49",
		timeOfPurchase: "2021-06-02T13:32:08.968Z",
		products: [
			{
				product: "avocados",
				price: 6.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 7.47,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 8.75,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 3.33,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 5.68,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 31.79,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 4443,
		misc: "",
		store: 1,
	},
	{
		id: "50",
		timeOfPurchase: "2021-08-06T19:38:57.625Z",
		products: [
			{
				product: "rocket salad",
				price: 7.18,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 6.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 1.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 1.06,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 8.49,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 24.24,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		id: "51",
		timeOfPurchase: "2021-06-24T21:46:59.755Z",
		products: [
			{
				product: "quinoa",
				price: 3.8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 7.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 6.84,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 2.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 1.27,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 2.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 6.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 2.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 8.52,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 6.62,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 48.19,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		store: 1,
	},
	{
		id: "52",
		timeOfPurchase: "2021-05-31T11:09:51.451Z",
		products: [
			{
				product: "Oatmeal Raisin Cookies",
				price: 6.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 7.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 3.17,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 17.44,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		store: 1,
	},
	{
		id: "53",
		timeOfPurchase: "2021-08-01T18:56:57.043Z",
		products: [
			{
				product: "brie",
				price: 8.07,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 3.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 5.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 7.87,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 4.96,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 4.99,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 34.02,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		store: 1,
	},
	{
		id: "54",
		timeOfPurchase: "2021-07-20T03:13:59.377Z",
		products: [
			{
				product: "pork belly slices",
				price: 8.18,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 6.15,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 3.07,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 5.57,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 7.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 1.05,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 31.15,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		store: 1,
	},
	{
		id: "55",
		timeOfPurchase: "2021-07-06T02:58:46.626Z",
		products: [
			{
				product: "rocket salad",
				price: 6.99,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 8.03,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 3.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 7.86,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 26.31,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		id: "56",
		timeOfPurchase: "2021-06-11T05:17:42.412Z",
		products: [
			{
				product: "mustard",
				price: 1.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 4.65,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 4.18,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 5.58,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 16.31,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		id: "57",
		timeOfPurchase: "2021-06-05T04:22:30.183Z",
		products: [
			{
				product: "cheese",
				price: 1.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 3.03,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 5.99,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 4.6,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 15.43,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		store: 1,
	},
	{
		id: "58",
		timeOfPurchase: "2021-06-04T10:12:43.687Z",
		products: [
			{
				product: "salami",
				price: 7.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 2.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 5.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 2.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 2.26,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 5.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 3.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 3.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 2.75,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 7.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 3.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 5.94,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 51.63,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		id: "59",
		timeOfPurchase: "2021-05-31T22:20:23.371Z",
		products: [
			{
				product: "orange juice",
				price: 8.55,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 3.83,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 5.87,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 8.05,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 1.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 1.16,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 6.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 2.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 5.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 7.55,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 2.77,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 5.69,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 58.4,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		id: "60",
		timeOfPurchase: "2021-06-18T20:06:40.955Z",
		products: [
			{
				product: "tapioca",
				price: 1.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 6.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 2.03,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 5.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 8.47,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 6.18,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 4.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 3.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 4.52,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 8.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 6.59,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 57.98,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		id: "61",
		timeOfPurchase: "2021-06-04T11:18:58.291Z",
		products: [
			{
				product: "Sugar Cookies",
				price: 8.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 4.3,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 1.78,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 7.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 1.52,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 5.75,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 6.91,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 37.05,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 4443,
		misc: "",
		store: 1,
	},
	{
		id: "62",
		timeOfPurchase: "2021-07-05T12:51:37.737Z",
		products: [
			{
				product: "chips",
				price: 2.58,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 1.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 8.57,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 3.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 1.82,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 17.58,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		store: 1,
	},
	{
		id: "63",
		timeOfPurchase: "2021-07-29T18:26:41.923Z",
		products: [
			{
				product: "cheese",
				price: 4.14,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 1.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 8.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 8.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 3.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 3.28,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 2.8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 3.17,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 1.16,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 8.14,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 44.16,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 4443,
		misc: "",
		store: 1,
	},
	{
		id: "64",
		timeOfPurchase: "2021-07-18T14:22:02.915Z",
		products: [
			{
				product: "chorizo",
				price: 4.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 3.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 8.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 8.94,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 6.14,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 4.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 2.02,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 7.59,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 45.55,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		store: 1,
	},
	{
		id: "65",
		timeOfPurchase: "2021-08-01T23:16:24.400Z",
		products: [
			{
				product: "sausages",
				price: 2.3,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 1.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 4.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 6.3,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 1.06,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 8.52,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 3.03,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 8.17,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 7.72,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 43.01,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		store: 1,
	},
	{
		id: "66",
		timeOfPurchase: "2021-07-15T18:16:20.910Z",
		products: [
			{
				product: "Shortbread Cookies",
				price: 7.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 7.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 2.25,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 5.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 6.38,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 2.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 5.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 8.15,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 6.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 8.17,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 4.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 8.08,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 73.65,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		store: 1,
	},
	{
		id: "67",
		timeOfPurchase: "2021-05-27T09:59:21.650Z",
		products: [
			{
				product: "Macaroon Cookies",
				price: 4.32,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 4.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 4.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 4.06,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 1.15,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 18.45,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		id: "68",
		timeOfPurchase: "2021-06-18T11:49:21.074Z",
		products: [
			{
				product: "tapioca",
				price: 7.58,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 2.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 5.45,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 15.63,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		store: 1,
	},
	{
		id: "69",
		timeOfPurchase: "2021-07-07T22:49:15.902Z",
		products: [
			{
				product: "bread",
				price: 4.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 3.83,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 3.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 6.98,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 2.96,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 2.87,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 1.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 8.79,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 2.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 5.48,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 42.6,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		store: 1,
	},
	{
		id: "70",
		timeOfPurchase: "2021-06-02T00:16:40.765Z",
		products: [
			{
				product: "sausages",
				price: 3.7,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 2.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 4.26,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 4.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 8.98,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 6.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 7.38,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 37.67,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		id: "71",
		timeOfPurchase: "2021-06-29T15:25:15.187Z",
		products: [
			{
				product: "milk",
				price: 2.87,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 5.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 2.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 1.16,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 11.91,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		id: "72",
		timeOfPurchase: "2021-05-29T09:25:27.297Z",
		products: [
			{
				product: "lettuce",
				price: 7.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 3.07,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 3.26,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 7.32,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 5.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 4.55,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 31.8,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		store: 1,
	},
	{
		id: "73",
		timeOfPurchase: "2021-06-27T05:23:58.795Z",
		products: [
			{
				product: "sweet chili sauce",
				price: 8.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 7.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 2.7,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 3.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 3.77,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 5.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 8.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 6.77,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 3.38,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 4.06,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 5.31,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 57.92,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		id: "74",
		timeOfPurchase: "2021-07-06T02:21:00.053Z",
		products: [
			{
				product: "Sugar Cookies",
				price: 2.26,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 2.26,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		store: 1,
	},
	{
		id: "75",
		timeOfPurchase: "2021-07-28T17:03:17.316Z",
		products: [
			{
				product: "white wine",
				price: 2.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 1.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 7.96,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 7.84,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 5.73,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 25.05,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		store: 1,
	},
	{
		id: "76",
		timeOfPurchase: "2021-06-21T12:29:58.658Z",
		products: [
			{
				product: "tomatoes",
				price: 5.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 1.79,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 4.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 5.29,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 6.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 8.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 5.03,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 4.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 7.14,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 50.03,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		id: "77",
		timeOfPurchase: "2021-06-30T23:28:30.060Z",
		products: [
			{
				product: "Gingerbread Cookies",
				price: 3.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 7.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 8.57,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 3.84,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 2.35,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 4.51,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 30.63,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		store: 1,
	},
	{
		id: "78",
		timeOfPurchase: "2021-07-15T21:19:24.105Z",
		products: [
			{
				product: "red wine",
				price: 5.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 2.92,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 3.61,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 4.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 8.18,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 2.21,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 27.32,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		id: "79",
		timeOfPurchase: "2021-07-20T00:38:05.799Z",
		products: [
			{
				product: "cheese",
				price: 7.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 2.53,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 1.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 2.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 5.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 3.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 4.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 5.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 8.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 5.27,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 46.12,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		store: 1,
	},
	{
		id: "80",
		timeOfPurchase: "2021-06-03T19:57:31.009Z",
		products: [
			{
				product: "Macaroon Cookies",
				price: 8.53,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 7.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 1.75,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 5.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 4.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 3.75,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 4.77,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 3.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 7.79,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 2.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 8.4,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 57.63,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		store: 1,
	},
	{
		id: "81",
		timeOfPurchase: "2021-07-24T12:43:15.021Z",
		products: [
			{
				product: "rump steak",
				price: 3.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 7.07,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 7.58,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 2.07,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 4.71,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 1.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 6.46,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 32.25,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		id: "82",
		timeOfPurchase: "2021-07-05T17:14:39.865Z",
		products: [
			{
				product: "cucumber",
				price: 3.99,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 3.99,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		id: "83",
		timeOfPurchase: "2021-07-21T06:32:59.917Z",
		products: [
			{
				product: "Macaron Cookies",
				price: 2.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 6.07,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 7.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 4.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 5.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 8.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 5.12,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 40.11,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		store: 1,
	},
	{
		id: "84",
		timeOfPurchase: "2021-07-28T21:31:35.406Z",
		products: [
			{
				product: "white wine",
				price: 3.28,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 7.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 2.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 1.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 8.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 3.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 8.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 2.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 7.46,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 2.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 6.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 6.11,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 60.45,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
	{
		id: "85",
		timeOfPurchase: "2021-07-18T12:13:34.372Z",
		products: [
			{
				product: "tapioca",
				price: 8.78,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 8.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 2.26,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 19.67,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		id: "86",
		timeOfPurchase: "2021-07-30T17:51:03.471Z",
		products: [
			{
				product: "ketchup",
				price: 4.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 4.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 2.94,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 6.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 4.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 5.77,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 2.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 2.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 2.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 6.84,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 8.07,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 4.28,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 56,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		store: 1,
	},
	{
		id: "87",
		timeOfPurchase: "2021-06-17T20:37:40.452Z",
		products: [
			{
				product: "heineken",
				price: 2.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 3.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 1.16,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 5.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 5.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 3.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 3.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 7.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 5.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 1.1,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 39,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		store: 1,
	},
	{
		id: "88",
		timeOfPurchase: "2021-06-02T06:11:19.389Z",
		products: [
			{
				product: "sorghum",
				price: 4.92,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 7.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 8.35,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 2.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 3.71,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 7.79,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 3.78,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 4.65,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 43.01,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		store: 1,
	},
	{
		id: "89",
		timeOfPurchase: "2021-06-12T11:56:17.453Z",
		products: [
			{
				product: "chorizo",
				price: 3.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 8.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 6.16,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 3.02,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 1.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 3.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 6.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 3.16,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 35.69,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		store: 1,
	},
	{
		id: "90",
		timeOfPurchase: "2021-07-31T21:51:54.621Z",
		products: [
			{
				product: "fanta",
				price: 1.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 1.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 8.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 5.78,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 3.48,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 21.06,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		store: 1,
	},
	{
		id: "91",
		timeOfPurchase: "2021-06-09T05:04:52.096Z",
		products: [
			{
				product: "brown rice",
				price: 5.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 2.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 5.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 7.25,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 8.53,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 3.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 2.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 6.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 5.4,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 48.07,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		id: "92",
		timeOfPurchase: "2021-06-20T01:32:50.169Z",
		products: [
			{
				product: "Macaroon Cookies",
				price: 2.26,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 2.26,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		store: 1,
	},
	{
		id: "93",
		timeOfPurchase: "2021-06-11T21:32:15.093Z",
		products: [
			{
				product: "bread",
				price: 5.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 4.7,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 8.46,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 1.52,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 20.49,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		store: 1,
	},
	{
		id: "94",
		timeOfPurchase: "2021-07-30T21:34:43.760Z",
		products: [
			{
				product: "milk",
				price: 8.05,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 2.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 8.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 1.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 1.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 1.05,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 8.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 4.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 8.05,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 2.76,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 46.2,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		store: 1,
	},
	{
		id: "95",
		timeOfPurchase: "2021-07-23T12:55:03.248Z",
		products: [
			{
				product: "Macaroon Cookies",
				price: 1.28,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 7.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 2.27,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 4.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 3.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 3.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 2.71,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 5.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 7.7,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 5.16,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 7.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 8.45,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 60.01,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		store: 1,
	},
	{
		id: "96",
		timeOfPurchase: "2021-07-05T19:51:24.815Z",
		products: [
			{
				product: "cucumber",
				price: 3.16,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 4.71,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 6.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 4.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 1.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 7.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 5.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 6.47,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 3.12,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 43.32,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		store: 1,
	},
	{
		id: "97",
		timeOfPurchase: "2021-08-02T03:22:10.628Z",
		products: [
			{
				product: "tapioca",
				price: 3.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 1.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 6.71,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 3.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 2.78,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 8.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 6.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 6.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 3.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 2.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 7.07,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 51.42,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		store: 1,
	},
	{
		id: "98",
		timeOfPurchase: "2021-06-26T21:12:52.723Z",
		products: [
			{
				product: "coca cola",
				price: 3.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 3.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 2.35,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 5.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 8.74,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 24.36,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		store: 1,
	},
	{
		id: "99",
		timeOfPurchase: "2021-06-09T04:04:56.677Z",
		products: [
			{
				product: "Chocolate Chip Cookies",
				price: 8.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 6.26,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 4.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 7.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 3.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 8.06,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 1.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 2.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 3.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 5.94,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 2.55,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 54.73,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		store: 1,
	},
];

let i = 0;
async function sendReceipt() {
	console.log(receipts[i]);
	const url = "http://localhost:3005/receipts";
	const response = await fetch(url, {
		method: "POST",
		mode: "cors",
		body: JSON.stringify(receipts[i]),
		headers: {
			"Content-Type": "application/json",
			// 'Content-Type': 'application/x-www-form-urlencoded',
		},
	});
	const body = await response.json();
	const div = document.getElementById("div");
	div.innerHTML = body.qrcode;
	i += 1;
}

const button = document.getElementById("button");
button.onclick = sendReceipt;
