const receipts = [
	{
		timeOfPurchase: "2021-06-24T07:54:42.017Z",
		products: [
			{
				product: "frozen peas",
				price: 8.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 8.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 1.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 5.07,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 23.07,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-13T11:30:25.086Z",
		products: [
			{
				product: "oat milk",
				price: 4.17,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 2.07,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 5.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 4.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 1.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 1.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 8.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 5.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 8.21,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 41.39,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-27T22:29:54.020Z",
		products: [
			{
				product: "wild rice",
				price: 8.52,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 7.06,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 15.58,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-11T20:46:15.189Z",
		products: [
			{
				product: "avocados",
				price: 2.02,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 2.02,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-08-07T20:42:53.619Z",
		products: [
			{
				product: "wild rice",
				price: 2.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 8.87,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 11.47,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-19T14:37:34.118Z",
		products: [
			{
				product: "cookies",
				price: 1.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 7.99,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 7.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 2.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 6.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 8.95,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 5.57,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 6.34,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 46.31,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-08-04T22:26:30.815Z",
		products: [
			{
				product: "sausages",
				price: 7.47,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 3.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 6.65,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 7.92,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 25.63,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-05T15:28:15.389Z",
		products: [
			{
				product: "chips",
				price: 7.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 7.3,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 1.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 2.01,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 17.64,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-11T05:36:12.205Z",
		products: [
			{
				product: "Chocolate Chip Cookies",
				price: 6.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 6.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 5.95,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 2.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 4.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 8.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 1.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 1.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 5.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 1.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 4.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 6.34,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 55.8,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-15T16:20:55.815Z",
		products: [
			{
				product: "amaranth",
				price: 8.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 2.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 2.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 3.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 2.2,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 19.1,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-22T14:49:50.285Z",
		products: [
			{
				product: "rocket salad",
				price: 7.06,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 3.32,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 6.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 5.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 2.38,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 7.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 8.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 4.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 7.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 8.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 4.25,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 1.5,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 66.28,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-20T01:33:47.565Z",
		products: [
			{
				product: "chorizo",
				price: 1.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 7.92,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 9.61,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-08-06T09:06:43.734Z",
		products: [
			{
				product: "Chocolate Chip Cookies",
				price: 8.75,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 7.26,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 5.03,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 6.3,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 3.57,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 2.58,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 3.38,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 6.44,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 8.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 7.85,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 4.42,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 65.24,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-24T17:44:35.803Z",
		products: [
			{
				product: "cheese",
				price: 5.27,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 1.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 2.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 7.17,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 5.37,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 6.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 7.7,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 7.46,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 3.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 4.35,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 8.58,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 59.05,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-17T11:59:41.552Z",
		products: [
			{
				product: "bread",
				price: 3.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 4.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 2.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 2.5,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 13.3,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-26T08:35:02.460Z",
		products: [
			{
				product: "sausages",
				price: 7.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 2.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 1.92,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 1.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 2.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 4.79,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 6.57,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 26.86,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-14T06:19:14.738Z",
		products: [
			{
				product: "pork chops",
				price: 2.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 1.01,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 3.63,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-08-04T23:02:53.715Z",
		products: [
			{
				product: "bread",
				price: 1.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 5.38,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 4.37,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 3.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 7.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 7.25,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 3.2,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 32.94,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-11T21:06:45.534Z",
		products: [
			{
				product: "bread",
				price: 3.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 3.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 3.54,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 10.41,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 4443,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-13T01:20:11.468Z",
		products: [
			{
				product: "tapioca",
				price: 6.05,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 2.18,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 5.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 2.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 4.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 3.76,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 24.55,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-18T07:47:59.462Z",
		products: [
			{
				product: "sweet chili sauce",
				price: 2.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 2.58,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 5.18,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-25T07:49:41.914Z",
		products: [
			{
				product: "sweetcorn",
				price: 1.38,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 2.8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 4.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 7.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 4.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 2.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 3.28,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 7.7,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 5.04,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 39.05,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-13T23:48:56.715Z",
		products: [
			{
				product: "cucumber",
				price: 7.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 5.74,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 8.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 8.33,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 3.15,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 7.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 3.26,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 43.69,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 4443,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-02T00:09:10.779Z",
		products: [
			{
				product: "brown rice",
				price: 8.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 3.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 4.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 2.98,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 8.28,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 2.38,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 2.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 4.63,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 37.77,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-27T09:13:36.552Z",
		products: [
			{
				product: "buckwheat",
				price: 8.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 3.3,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 7.27,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 6.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 6.47,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 4.94,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 37.03,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-23T20:09:08.597Z",
		products: [
			{
				product: "arrowroot",
				price: 6.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 4.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 4.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 8.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 5.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 8.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 5.38,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 4.03,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 47.42,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-29T16:28:29.086Z",
		products: [
			{
				product: "sorghum",
				price: 4.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 8.83,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 7.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 7.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 3.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 5.05,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 36.74,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-08-11T00:22:13.112Z",
		products: [
			{
				product: "teff",
				price: 3.74,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 7.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 2.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 5.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 7.8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 3.34,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 29.8,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-22T14:06:44.854Z",
		products: [
			{
				product: "tooth brush",
				price: 3.8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 6.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 4.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 2.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 3.67,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 21.34,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-24T10:07:23.304Z",
		products: [
			{
				product: "wild rice",
				price: 6.07,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 6.35,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 2.8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 4.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 4.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 3.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 6.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 1.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 3.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 8.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 4.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 6.75,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 59.88,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-30T14:08:26.124Z",
		products: [
			{
				product: "sausages",
				price: 6.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 1.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 4.16,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 6.15,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 7.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 8.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 4.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 8.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 4.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 5.83,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 7.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 7.69,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 73.46,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-06T10:40:40.543Z",
		products: [
			{
				product: "Sugar Cookies",
				price: 8.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 8.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 3.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 5.77,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 7.24,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 32.7,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-05T14:26:59.643Z",
		products: [
			{
				product: "sausages",
				price: 6.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 2.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 1.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 7.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 3.02,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 6.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 1.27,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 7.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 7.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 6.84,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 3.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 7.25,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 60.07,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-08-11T14:01:40.090Z",
		products: [
			{
				product: "sorghum",
				price: 7.14,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 7.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 1.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 6.79,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 7.14,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 5.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 6.42,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 41.57,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-12T01:01:43.087Z",
		products: [
			{
				product: "sprite",
				price: 4.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 7.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 3.74,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 2.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 3.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 7.05,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 29.87,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-08-08T11:24:06.879Z",
		products: [
			{
				product: "mustard",
				price: 2.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 6.38,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 1.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 8.55,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 5.3,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 3.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 2.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 6.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 5.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 5.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 4.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 4.98,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 56.12,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-02T03:54:30.894Z",
		products: [
			{
				product: "heineken",
				price: 3.71,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 1.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 8.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 1.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 5.65,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 1.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 5.95,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 2.89,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 30.52,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-03T22:33:36.623Z",
		products: [
			{
				product: "milk",
				price: 7.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 8.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 2.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 2.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 6.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 6.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 2.46,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 4.75,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 7.85,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 49.4,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-30T19:10:05.939Z",
		products: [
			{
				product: "Shortbread Cookies",
				price: 1.94,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 2.7,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 4.64,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-01T19:34:17.052Z",
		products: [
			{
				product: "bread",
				price: 6.66,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 6.66,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-17T18:50:11.994Z",
		products: [
			{
				product: "white wine",
				price: 1.85,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 5.05,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 4.98,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 3.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 5.32,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 20.71,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-05T00:19:17.705Z",
		products: [
			{
				product: "rocket salad",
				price: 8.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 6.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 5.29,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 8.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 8.84,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 2.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 4.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 6.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 6.67,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 58.29,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-19T08:05:28.450Z",
		products: [
			{
				product: "pork belly slices",
				price: 2.03,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 2.96,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 3.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 5.53,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 2.43,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 16.64,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-06T22:36:58.736Z",
		products: [
			{
				product: "sausages",
				price: 5.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 5.02,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 10.25,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 4443,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-14T12:15:50.890Z",
		products: [
			{
				product: "teff",
				price: 7.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 3.35,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 3.92,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 3.99,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 2.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 5.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 8.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 5.52,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 5.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 8.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 6.11,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 61.86,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-19T10:53:10.360Z",
		products: [
			{
				product: "oat milk",
				price: 3.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 6.05,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 3.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 5.3,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 7.37,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 8.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 6.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 1.93,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 43.31,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-10T08:26:31.385Z",
		products: [
			{
				product: "ketchup",
				price: 4.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 7.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 4.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 8.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 3.58,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 8.26,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 1.75,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 6,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 44.88,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-05T12:39:20.663Z",
		products: [
			{
				product: "pepsi",
				price: 6.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 7.8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 4.77,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 3.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 2.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 1.74,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 3.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 6.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 2.18,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 3.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 2.95,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 44.25,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-18T13:39:54.896Z",
		products: [
			{
				product: "oat milk",
				price: 6.15,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 2.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 6.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 2.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 5.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 1.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 8.87,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 7.99,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 5.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 2.62,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 49.9,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-24T07:40:52.740Z",
		products: [
			{
				product: "arrowroot",
				price: 5.12,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 5.12,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-01T05:16:48.980Z",
		products: [
			{
				product: "stella",
				price: 3.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 7.15,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 6.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 2.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 1.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 7.06,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 6.6,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 34.98,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-11T17:51:25.470Z",
		products: [
			{
				product: "sprite",
				price: 1.77,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 1.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 2.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 5.36,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 10.79,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-12T16:01:50.985Z",
		products: [
			{
				product: "brown rice",
				price: 6.26,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 4.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 1.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 2.87,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 1.52,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 7.8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 6.04,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 30.5,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-26T02:26:48.789Z",
		products: [
			{
				product: "Macaroon Cookies",
				price: 8.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 2.41,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 6.96,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 2.15,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 6.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 5.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 6.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 7.61,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 7.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 4.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 1.79,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 8.69,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 69.48,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-29T12:59:06.909Z",
		products: [
			{
				product: "bread",
				price: 7.7,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 7.29,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 8.46,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 4.69,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 28.14,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-06T12:46:29.168Z",
		products: [
			{
				product: "sweetcorn",
				price: 5.74,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 5.74,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-13T01:44:17.707Z",
		products: [
			{
				product: "wild rice",
				price: 1.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 7.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 7.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 6.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Oatmeal Raisin Cookies",
				price: 3.35,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 27.22,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-10T00:50:23.068Z",
		products: [
			{
				product: "chips",
				price: 8.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 2.75,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 4.37,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 8.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 8.35,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 5.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 6.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 7.96,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 5.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 6.72,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 73.31,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-22T11:29:15.561Z",
		products: [
			{
				product: "oreos",
				price: 2.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 8.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 6.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 3.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 7.84,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 3.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 8.58,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 1.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 4.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 1.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 8.53,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 56.89,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-15T16:11:09.541Z",
		products: [
			{
				product: "Macaron Cookies",
				price: 3.5,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 3.5,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-13T18:07:17.693Z",
		products: [
			{
				product: "salami",
				price: 7.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 2.3,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 5.11,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 15.09,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-02T02:41:12.408Z",
		products: [
			{
				product: "stella",
				price: 4.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 6.3,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 6.98,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 1.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 4.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 4.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 5.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 7.1,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 40.51,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-10T07:12:45.015Z",
		products: [
			{
				product: "pork belly slices",
				price: 8.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 7.35,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 5.25,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 8.27,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 7.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 7.01,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 3.47,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 1.71,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 5.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 3.63,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 57.81,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-08-09T00:17:08.169Z",
		products: [
			{
				product: "tooth brush",
				price: 8.14,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 6.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 7.99,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 1.38,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 2.8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 1.02,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 27.67,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-08-08T13:10:41.807Z",
		products: [
			{
				product: "millet",
				price: 4.74,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 5.16,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 1.92,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 6.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 2.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 4.77,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 8.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "orange juice",
				price: 2.25,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 5.24,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 1.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 8.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 5.15,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 56.79,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-08-09T05:23:10.601Z",
		products: [
			{
				product: "Biscotti Cookies",
				price: 7.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 8.75,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 8.49,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 24.55,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-06T03:58:10.988Z",
		products: [
			{
				product: "cookies",
				price: 3.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 4.22,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 6.61,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 5.38,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 8.94,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 3.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 3.44,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 1.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 7.95,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 8.82,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 58.77,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-30T07:02:18.427Z",
		products: [
			{
				product: "buckwheat",
				price: 2.18,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 4.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rump steak",
				price: 7.06,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 2.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 7.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 7.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 4.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 2.31,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 37.28,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 4443,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-05T07:06:32.489Z",
		products: [
			{
				product: "cookies",
				price: 3.58,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 7.57,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 1.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 2.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 7.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 1.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 3.99,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 28.86,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-24T16:20:16.053Z",
		products: [
			{
				product: "red wine",
				price: 1.61,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 1.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 2.6,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 5.52,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-01T16:16:44.633Z",
		products: [
			{
				product: "mustard",
				price: 7.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 1.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 4.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 1.57,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 5.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "milk",
				price: 5.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 2.25,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 8.41,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 37.01,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-21T15:22:42.941Z",
		products: [
			{
				product: "wild rice",
				price: 6.7,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 2.61,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 7.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 7.67,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 24.61,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3852,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-01T03:17:11.215Z",
		products: [
			{
				product: "coca cola",
				price: 3.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 2.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 2.43,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 3.3,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 8.47,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 20.19,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2229,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-08-09T12:02:21.045Z",
		products: [
			{
				product: "amaranth",
				price: 5.89,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 7.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 1.99,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 7.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Chocolate Chip Cookies",
				price: 8.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 4.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 5.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 2.94,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 44.67,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-31T16:16:48.328Z",
		products: [
			{
				product: "ketchup",
				price: 8.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 1.14,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 1.65,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 5.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sorghum",
				price: 4.54,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 1.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 5.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 4.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 7.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 8.04,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 48.21,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-06T20:39:20.609Z",
		products: [
			{
				product: "chorizo",
				price: 2.65,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 8.29,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 4.92,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 6.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 1.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 7.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 8.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 7.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 5.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 8.14,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 7.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "bread",
				price: 1.56,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 70.06,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-21T09:09:28.566Z",
		products: [
			{
				product: "Sugar Cookies",
				price: 2.85,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 8.05,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 3.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 2.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 8.52,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 4.6,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 7.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 1.69,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 38.56,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 3846,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-24T22:12:18.206Z",
		products: [
			{
				product: "amaranth",
				price: 4.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 8.75,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 2.26,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 15.24,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-31T18:51:07.126Z",
		products: [
			{
				product: "tooth brush",
				price: 5.2,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 7.14,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 5.28,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 17.62,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7777,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-17T14:12:39.465Z",
		products: [
			{
				product: "rocket salad",
				price: 3.71,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 1.79,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 7.09,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 6.42,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 6.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 6.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 1.8,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 5.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 4.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 1.72,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 45.19,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-07T13:26:20.458Z",
		products: [
			{
				product: "pepsi",
				price: 6.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork chops",
				price: 7.16,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 7.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 2.52,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 2.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 5.73,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 1.6,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 34.03,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-06T15:21:39.977Z",
		products: [
			{
				product: "bread",
				price: 1.87,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 5.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 3.9,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 2.92,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 1.33,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 2.94,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brown rice",
				price: 1.19,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 6.7,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 1.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 8.7,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 36.88,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-21T10:28:36.152Z",
		products: [
			{
				product: "coca cola zero",
				price: 7.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 2.3,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 7.27,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cheese",
				price: 1.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 2.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 8.27,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 5.93,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 6.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 3.99,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 45.46,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-28T01:43:24.888Z",
		products: [
			{
				product: "rocket salad",
				price: 2.23,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 2.64,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 3.96,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 2.04,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 3.65,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 14.52,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-24T00:55:29.461Z",
		products: [
			{
				product: "Macaroon Cookies",
				price: 7.15,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "brie",
				price: 7.46,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 1.85,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 2.85,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 6.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 2.37,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 1.78,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 29.91,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-05T04:22:30.187Z",
		products: [
			{
				product: "pork chops",
				price: 8.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 6.95,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 1.46,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 16.77,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-03T13:52:52.270Z",
		products: [
			{
				product: "Macaroon Cookies",
				price: 5.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Shortbread Cookies",
				price: 8.92,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tomatoes",
				price: 4.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "millet",
				price: 3.44,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 21.59,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-26T17:58:52.414Z",
		products: [
			{
				product: "millet",
				price: 1.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 8.1,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salami",
				price: 6.84,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 8.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 3.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 6.62,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 35.92,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1114,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-13T21:17:58.792Z",
		products: [
			{
				product: "pork belly slices",
				price: 3.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 4.63,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 1.15,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 5.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 1.03,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 15.7,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-04T12:46:05.072Z",
		products: [
			{
				product: "bread",
				price: 6.32,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 5.94,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 8.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 2.92,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 8.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 4.32,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 7.57,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 44.06,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-17T09:16:57.070Z",
		products: [
			{
				product: "amaranth",
				price: 4.68,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tooth brush",
				price: 5.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 1.7,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cucumber",
				price: 3.49,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 5.11,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "red wine",
				price: 7.26,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 27.35,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-26T20:55:37.805Z",
		products: [
			{
				product: "white wine",
				price: 5.95,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "rocket salad",
				price: 1.35,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 7.51,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 8.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 8.78,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Sugar Cookies",
				price: 3.82,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 5.28,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "tapioca",
				price: 5.4,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 8.13,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola zero",
				price: 1.59,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 2.72,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 58.92,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-08-06T03:10:23.396Z",
		products: [
			{
				product: "heineken",
				price: 4.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "arrowroot",
				price: 7.55,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "crips",
				price: 8.7,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 20.97,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 9998,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-24T06:13:14.002Z",
		products: [
			{
				product: "quinoa",
				price: 1.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "white wine",
				price: 6.62,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Gingerbread Cookies",
				price: 1.88,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 7.91,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 2.32,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 8.77,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 6.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 8.99,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "coca cola",
				price: 5.95,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 8.32,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 7,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 65.77,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5533,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-27T19:47:53.930Z",
		products: [
			{
				product: "oreos",
				price: 3.67,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "teff",
				price: 7.39,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "avocados",
				price: 8.94,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 2.11,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 22.11,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 2221,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-06-13T08:59:53.193Z",
		products: [
			{
				product: "millet",
				price: 4.21,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 8.86,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sprite",
				price: 5.81,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweet chili sauce",
				price: 6.45,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Biscotti Cookies",
				price: 7.08,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 5.92,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 2.93,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 41.26,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-20T14:13:07.919Z",
		products: [
			{
				product: "white wine",
				price: 5.92,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "wild rice",
				price: 7.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "lettuce",
				price: 6.31,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sweetcorn",
				price: 6.69,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chicken breast 450g",
				price: 6.28,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oreos",
				price: 4.44,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chips",
				price: 7.79,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaroon Cookies",
				price: 4.72,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 5.03,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "ketchup",
				price: 1.33,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "buckwheat",
				price: 8.5,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "heineken",
				price: 2.16,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 66.86,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 5768,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-14T15:23:17.108Z",
		products: [
			{
				product: "Macaron Cookies",
				price: 8.48,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "cookies",
				price: 2.98,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "quinoa",
				price: 2.76,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "sausages",
				price: 8.25,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "mustard",
				price: 3.97,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "fanta",
				price: 1.49,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 27.93,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1254,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-14T01:23:04.414Z",
		products: [
			{
				product: "wild rice",
				price: 8.18,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pepsi",
				price: 2.44,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "stella",
				price: 6.94,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "salad",
				price: 6.36,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "amaranth",
				price: 8.34,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "Macaron Cookies",
				price: 7.12,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "pork belly slices",
				price: 8.66,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "oat milk",
				price: 8.17,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 56.21,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 7531,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
	{
		timeOfPurchase: "2021-07-22T23:55:20.649Z",
		products: [
			{
				product: "pork belly slices",
				price: 8.56,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "chorizo",
				price: 1.26,
				vat: 0.2,
				isRefunded: false,
			},
			{
				product: "frozen peas",
				price: 1.02,
				vat: 0.2,
				isRefunded: false,
			},
		],
		total: 10.84,
		currency: "£",
		paymentMethod: "card",
		cardNumber: 1133,
		misc: "",
		storeId: "k5",
		categoryId: "jR",
	},
];

let i = 0;
async function sendReceipt() {
	console.log(receipts[i]);
	const url = "http://localhost:3005/receipts";
	const response = await fetch(url, {
		method: "POST",
		mode: "cors",
		body: JSON.stringify(receipts[i]),
		headers: {
			"Content-Type": "application/json",
			// 'Content-Type': 'application/x-www-form-urlencoded',
		},
	});
	const body = await response.json();
	const div = document.getElementById("div");
	div.innerHTML = body.qrcode;
	i += 1;
}

const button = document.getElementById("button");
button.onclick = sendReceipt;
